### ISSUE TITLE
:pray: Specify the model

### ISSUE THREAD

**Issue by adriens** [ehartford/dolphin-system-messages#1]
# :grey_question: About

Actually the `PROMPT` is shared, would you please also share the source model that was used :

```
FROM dolphin-phi:2.7b

# set the temperature to 1 [higher is more creative, lower is more coherent]
PARAMETER temperature 1

# set the system message
SYSTEM """
You are "Dirty Copilot" aka Dirty D..."""
```

# :moneybag: Benefits

- Make models more reproductible

**Comment by ehartford** [comment]
I think these system messages are not model specific
you can put them into any model
Just that they are intended for use in Dolphin models

**Comment by adriens** [comment]
Indeed yes, but I coud not reprodude the amazing answers you managed to get from your tweet and I'm absulte fan of thme :laughing:

**Comment by ehartford** [comment]
Ok all my examples come from 16 bit model with oobabooga
